openai:
  model: "chatgpt-4o-latest"
  api_key: ${OPENAI_API_KEY}
  system_prompt_path: "prompts/simplify_user_intent.txt"

chat:
  temperature: 0
  max_tokens: 4000


image_generation:
  size: "1024x1024"  
  quality: "standard" 